name: abalone-mlops
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - black
  - isort
  - flake8
  - prefect
  - pydantic
  - numpy
  - scikit-learn=1.2.2
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - xgboost=1.7.3
  - pip:
      - mlflow==2.6.0
      - kagglehub==0.3.3
      - piptools
