name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']  

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment with the selected version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies (both production and development)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in
          pip install -r requirements-dev.in

      # Step 4: Run isort (check import order)
      - name: Run isort
        run: isort --check --diff .

      # Step 5: Run black (check code formatting)
      - name: Run black
        run: black --check . --max-line-length 88

      # Step 6: Run flake8 (check for linting issues)
      - name: Run flake8
        run: flake8 . --max-line-length 88

      # Step 7: Run tests
      - name: Run tests
        run: pytest

      # Step 8: Cache dependencies (optional, for speed)
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
